### ISSUE TITLE
Question fastPlace

### ISSUE THREAD

**Issue by OakP** [Crimz8n/havook-1.12.2#2]
Hello, I have some question about your FastPlace.I understand that you changed the library code, and added cfg to build.gradle. But, I tried to do this before and it didn't work for me in my client. If you don't mind, could you explain why it doesn't work for me and why it works for you ? It would help me a lot with another thing!

**Comment by rayferric** [comment]
Just for the sake of closing this issue, I have used so called **[access transformer](https://mcforge.readthedocs.io/en/latest/advanced/accesstransformers/)** to expose a private member, `rightClickDelayTimer`. In Forge 1.12.2-14.23.5.2854, configuring access transformers is just a matter of setting two options in your `build.gradle`.

* ./build.gradle

```groovy
minecraft {
	accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
}

jar {
	manifest.attributes('FMLAT': 'accesstransformer.cfg')
}
```

* ./src/main/resources/META-INF/accesstransformer.cfg

```
public net.minecraft.client.Minecraft field_71467_ac # rightClickDelayTimer
```
